#!/bin/bash
FW=`ls /usr/share/bmgui/fw/bsfw* -1 | grep -v backup`
SERVER_IP=`expr "\`cat $HOME/.bmgui/bmgui.xml\`" : '.*server_addr" value="\([0-9]*.[0-9]*.[0-9]*.[0-9]*\)'`
sudo bmgui_flash $SERVER_IP $FW
RET=$?
echo $RET > /tmp/flash_status
sleep 3


[bm@bm ~]$ cat /usr/bin/bmgui_start 
#!/bin/bash

#Already run?
if [ `ps -A u| grep bmgui | grep -v grep| grep -v bmgui_start -c` -gt 0 ]; then
  echo "bmgui already run";
  exit 1
fi

export MOUSE="1"

lsusb -v > /tmp/lsusb 2> /dev/null

if [ `grep -i Tenx -c /tmp/lsusb` -eq 0 ]; then
  amixer sset Master 100%
else
  amixer sset PCM 100%
fi

if [ `grep -i mouse -c /tmp/lsusb` -eq 0 ]; then
  export MOUSE="0"
fi

if [ `grep -i egalax -c /tmp/lsusb` -gt 0 ] || [ `grep -i 1aad:0001 -c /tmp/lsusb` -gt 0 ]; then
    export MOUSE="2";
fi

rm /tmp/lsusb

SERVER_IP=`expr "\`cat $HOME/.bmgui/bmgui.xml\`" : '.*server_addr" value="\([0-9]*.[0-9]*.[0-9]*.[0-9]*\)'`
export SERVER_ON="true"

if [ `ping $SERVER_IP -c 1 -W 1 | grep -c req=1` -eq 0 ]; then
  export SERVER_ON="false"
fi

DEFAULT_ROUTER=`netstat -r -n | awk '/^0.0.0.0/ {print}'`
DEFAULT_GW=`echo $DEFAULT_ROUTER | awk '{print($2)}'`
INT=`echo $DEFAULT_ROUTER | awk '{print($8)}'`
IFCONFIG=`ifconfig $INT`
IP_ADDRESS=`expr "$IFCONFIG" : '.*inet\s\(.*\)\snetmask'`
NETMASK=`expr "$IFCONFIG" : '.*Mask:\([0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\).*'`
RESOLV=`cat /etc/resolv.conf`
DNS=`expr "$RESOLV" : '.*nameserver \([0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\).*'`

if [ `ping $DEFAULT_GW -c 1 -W 1 | grep -c req=1` -gt 0 ]; then
  VLIST=`curl http://www.sibek.ru/repo/17/x86_64/ --connect-timeout 1 2> /dev/null`
  LASTVER=`expr "$VLIST" : '.*bmgui-\([0-9]*\.[0-9]*-[0-9]*\)\.'`
fi

sync

bmgui --gateway="$DEFAULT_GW" --local_addr="$IP_ADDRESS" --netmask="$NETMASK" --dns="$DNS" --input_dev="$MOUSE" --server_status="$SERVER_ON" --available_update_version="$LASTVER"
RET=$?

while true; do

  echo $RET

  if [ $RET -eq 13 ]; then
    VER1=`cat /etc/bminfo`
    roxterm -e bmgui_update&
    wait $!
    VER2=`cat /etc/bminfo`
    if [ "$VER1" = "$VER2" ]; then
      bmgui --gateway="$DEFAULT_GW" --local_addr="$IP_ADDRESS" --netmask="$NETMASK" --dns="$DNS" --input_dev="$MOUSE" --server_status="$SERVER_ON" --available_update_version="$LASTVER" --updated=0
      RET=$?
    else
      bmgui --gateway="$DEFAULT_GW" --local_addr="$IP_ADDRESS" --netmask="$NETMASK" --dns="$DNS" --input_dev="$MOUSE" --server_status="$SERVER_ON" --available_update_version="$LASTVER" --updated=1
      RET=$?
    fi
  else
    if [ $RET -eq 169 ]; then
      roxterm -e bmgui_update_fw&
      wait $!
      FS="1"
      FS=`cat /tmp/flash_status`
      rm /tmp/flash_status
      if [ $FS -eq 0 ]; then
        bmgui --gateway="$DEFAULT_GW" --local_addr="$IP_ADDRESS" --netmask="$NETMASK" --dns="$DNS" --input_dev="$MOUSE" --server_status="$SERVER_ON" --available_update_version="$LASTVER" --updatedfw=1
        RET=$?
      else
        bmgui --gateway="$DEFAULT_GW" --local_addr="$IP_ADDRESS" --netmask="$NETMASK" --dns="$DNS" --input_dev="$MOUSE" --server_status="$SERVER_ON" --available_update_version="$LASTVER" --updatedfw=0
        RET=$?
      fi
    else
      if [ $RET -eq 0 ]; then
        exit 0
      else
        exit 1
      fi
    fi
  fi
done
