#!/bin/bash

#Already run?
if [ `ps -A u| grep bmgui | grep -v grep| grep -v bmgui_start -c` -gt 0 ]; then
  echo "bmgui already run";
  exit 1
fi

export MOUSE="1"

lsusb -v > /tmp/lsusb 2> /dev/null

if [ `grep -i Tenx -c /tmp/lsusb` -eq 0 ]; then
  amixer sset Master 100%
else
  amixer sset PCM 100%
fi

if [ `grep -i mouse -c /tmp/lsusb` -eq 0 ]; then
  export MOUSE="0"
fi

if [ `grep -i egalax -c /tmp/lsusb` -gt 0 ] || [ `grep -i 1aad:0001 -c /tmp/lsusb` -gt 0 ]; then
    export MOUSE="2";
fi

rm /tmp/lsusb

SERVER_IP=`expr "\`cat $HOME/.bmgui/bmgui.xml\`" : '.*server_addr" value="\([0-9]*.[0-9]*.[0-9]*.[0-9]*\)'`
export SERVER_ON="true"

if [ `ping $SERVER_IP -c 1 -W 1 | grep -c req=1` -eq 0 ]; then
  export SERVER_ON="false"
fi

DEFAULT_ROUTER=`netstat -r -n | awk '/^0.0.0.0/ {print}'`
DEFAULT_GW=`echo $DEFAULT_ROUTER | awk '{print($2)}'`
INT=`echo $DEFAULT_ROUTER | awk '{print($8)}'`
IFCONFIG=`ifconfig $INT`
IP_ADDRESS=`expr "$IFCONFIG" : '.*addr:\(.*\)\sBcast'`
NETMASK=`expr "$IFCONFIG" : '.*Mask:\([0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\).*'`
RESOLV=`cat /etc/resolv.conf`
DNS=`expr "$RESOLV" : '.*nameserver \([0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\).*'`

if [ `ping $DEFAULT_GW -c 1 -W 1 | grep -c req=1` -gt 0 ]; then
  VLIST=`curl http://www.sibek.ru/repo/x86_64/ --connect-timeout 1 2> /dev/null`
  LASTVER=`expr "$VLIST" : '.*bmgui-\([0-9]*\.[0-9]*-[0-9]*\)\.'`
fi

SETTINGS=`cat $HOME/.bmgui/bmgui.xml | grep -v "</clres:resources>" | grep -v local_addr | grep -v netmask | grep -v gateway | grep -v dns | grep -v input_dev| grep -v server_status| grep -v available_update_version`

echo $SETTINGS | sed -e 's/\/>/\/>\n/g' | sed -e 's/> </>\n </' > $HOME/.bmgui/bmgui.xml
echo " <clres:option clres:name=\"gateway\" value=\"$DEFAULT_GW\"/>" >> $HOME/.bmgui/bmgui.xml
echo " <clres:option clres:name=\"local_addr\" value=\"$IP_ADDRESS\"/>" >> $HOME/.bmgui/bmgui.xml
echo " <clres:option clres:name=\"netmask\" value=\"$NETMASK\"/>" >> $HOME/.bmgui/bmgui.xml
echo " <clres:option clres:name=\"dns\" value=\"$DNS\"/>" >> $HOME/.bmgui/bmgui.xml
echo " <clres:option clres:name=\"input_dev\" value=\"$MOUSE\"/>" >> $HOME/.bmgui/bmgui.xml
echo " <clres:option clres:name=\"server_status\" value=\"$SERVER_ON\"/>" >> $HOME/.bmgui/bmgui.xml
echo " <clres:option clres:name=\"available_update_version\" value=\"$LASTVER\"/>" >> $HOME/.bmgui/bmgui.xml
echo "</clres:resources>" >> $HOME/.bmgui/bmgui.xml

sync

bmgui

RET=$?

if [ $RET -eq 13 ]; then
  roxterm -e bmgui_update&
  wait $!
  bmgui
fi
