#!/usr/bin/php
<?php

$output = `xinput_calibrator`;
$output = explode("\n",$output);

$xinput = array();

for($i=0;$i<count($output);$i++)
{
  $output[$i] = trim($output[$i]);
  if(preg_match("/^xinput/u",$output[$i]))
  {
    $xinput[] = $output[$i];
  }
}

$data = '';
if ( ! $file = fopen("/etc/xdg/lxsession/LXDE/autostart","r") )
{
 exit(1);
}

while(!feof($file))
{
  $data .= fread($file,1024); 
}
fclose($file);

$newdata = array();
$data = explode("\n",$data);
for($i=0;$i<count($data);$i++)
{
  if(preg_match("/^@./u",$data[$i]))
  {
    if(preg_match("/@xinput/u",$data[$i])) continue;
    $newdata[] = $data[$i];
  }
}

for($i=0;$i<count($xinput);$i++)
{
  $newdata[] = "@".$xinput[$i];
}

$newdata = implode("\n",$newdata);
if ( $file = fopen("/etc/xdg/lxsession/LXDE/autostart","w") )
{
  fwrite($file,$newdata."\n");
  fclose($file);
  flush();
}
system('sync');

?>

